box resources/box.png 2 2 3 0
grass resources/billboardgrass.png 3 3 3 0
noise resources/noiseTexture.png 0 0 3 1
wall_white resources/WallWhite.png 2 2 3 0
wall_red resources/WallRed.png 2 2 3 0
wall_green resources/WallGreen.png 2 2 3 0
wall_yellow resources/WallYellow.png 2 2 3 0
wall_blue resources/WallBlue.png 2 2 3 0
water_normal_map resources/waterNormal.png 0 0 3 1